gemini:
  api_key: ${GEMINI_API_KEY}  # Will be loaded from environment/secrets
  # Available models to try:
  model: "gemini-2.0-flash"  # Primary model
  vision_model: "gemini-pro-vision"  # For images
  embedding_model: "embedding-001"  # For embeddings
  # Other models to try:
  # - gemini-pro
  # - gemini-pro-vision
  # - gemini-ultra
  # - gemini-ultra-vision

whisper_model: "openai/whisper-small" # choose from here https://huggingface.co/collections/openai/whisper-release-6501bba2cf999715fd953013

chromadb:
  chromadb_path: "chroma_db"
  collection_name: "pdfs"

chat_sessions_database_path: "./chat_sessions/chat_sessions.db"

openai:
  api_key: ${OPENAI_API_KEY}  # Will be loaded from environment/secrets
  model: "gpt-3.5-turbo"

ollama:
  base_url: "http://localhost:11434"
  model: "llama2"
